version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket tmv-lambdas --output-template-file new-template.yaml
artifacts:
  type: zip
  files:
    - new-template.yaml