AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A hello world application.
Parameters:
  Env:
    Description: Environment
    Default: dev
    Type: String
    AllowedValues: [dev, test, prod]
    ConstraintDescription: must specify dev, test or prod.
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Env}-hello-world-lambda"
      Handler: main.handler
      Runtime: python3.6
      CodeUri: src
      Events:
        Api:
          Type: Api
          Properties:
            Path: /hello
            Method: get